import { AppProvider } from "../components/AppContext"
import Header from "../components/layout/Header"
import './globals.css'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ subsets: ['latin'], weight: ["400", "500", "700"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-orange-100">
      <body className={roboto.className}>
        <main className='max-w-4xl mx-auto p-4'>
          <AppProvider>
            <Header></Header>
            {children}
          </AppProvider>
        </main>
      </body>
    </html>
  )
}